---
title: "Teaching"
---

## Courses
- **Data-intensive systems and applications (2ID70)** — In the era of Big Data and Data Science, the database and data engineering market is going through unprecedented shifts and challenges demanding new approaches for processing heterogeneous data at massive scale. As a result, a new breed of data management systems which aims to handle smart data-driven applications is emerging. This course prepares students to meet the new challenges of contemporary data engineering in which traditional assumptions break, where new data models, query languages and programming interfaces are required.
<br><b>TU/e students:</b> material available in canvas.
- **Big Data Management (2AMD15)** — We study models of contemporary data intensive systems and their practical use. These models are: Parallel and distributed data processing (MapReduce, etc.), Data Stream Management Systems and Approximate Query Processing. We discuss why these models were introduced, their relative advantages and disadvantages, how to use them in practice, and, at a high level, how they are implemented. Unlike the course Engineering Data-Intensive Systems (2IMD10) which focuses primarily on systems internals and their efficient implementation, the primary goal of this course is to develop the practical ability to engineer non-trivial data intensive applications based on a solid understanding of the underlying engineering principles. Towards this goal, hands-on practical assignment(s) using contemporary frameworks and technologies are a central component of the course. As a result, students who complete this course have a deep understanding of the state-of-the-art data management models, and how these can be applied in industrial and scientific context for enabling data-driven discoveries.
<br><b>TU/e students:</b> material available in canvas.

## Thesis topics
Before contacting us for a thesis topic, please consider the following:

- Thesis topics for the DAI cluster are announced centrally <a href="https://dai.win.tue.nl">here</a>.
- Most of the topics we offer build on the knowledge acquired in course 2AMD15. If you got a low grade in the course final exam, or did not like the course, you might prefer to graduate with a different group.
- We accept supervision of external internships and theses **only if the topic is highly relevant to the group's research focus**. This also means that the thesis should include a clear research question.
- We also expect our students to have followed the DB seminar, which is co-organized by the SODATA group.
